# Generated by Django 5.0.4 on 2024-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancel', 'Cancel')], default='created', max_length=20),
        ),
    ]
