# Generated by Django 5.0.4 on 2024-08-27 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_speechtotext_file_name_alter_user_credit_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian')], max_length=15, null=True)),
                ('type', models.CharField(blank=True, choices=[('article', 'Article'), ('interview', 'Interview'), ('news', 'News'), ('reportage', 'Reportage')], max_length=30, null=True)),
                ('output_docx', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('output_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('stt', 'Speech To Text'), ('summary', 'Summary'), ('article', 'Article'), ('translate', 'Translate')], max_length=30)),
                ('output_type', models.CharField(choices=[('text', 'Text'), ('docx', 'Docx')], max_length=30)),
                ('input_file', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('input_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian')], max_length=15, null=True)),
                ('output_docx', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('output_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian')], max_length=15, null=True)),
                ('output_docx', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('output_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
        migrations.RenameField(
            model_name='speechtotext',
            old_name='result_docx',
            new_name='output_docx',
        ),
        migrations.RenameField(
            model_name='speechtotext',
            old_name='result_text',
            new_name='output_text',
        ),
        migrations.RemoveField(
            model_name='speechtotext',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='speechtotext',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='speechtotext',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='speechtotext',
            name='voice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='users.project'),
        ),
        migrations.AddField(
            model_name='speechtotext',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stt', to='users.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='users.project'),
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translate', to='users.project'),
        ),
        migrations.AddField(
            model_name='translate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
