# Generated by Django 5.0.4 on 2024-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_article_project_summary_translate_delete_advert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechtotextForBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=255)),
                ('telegram_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'speechtotextforbot',
            },
        ),
        migrations.RemoveField(
            model_name='speechtotext',
            name='lang',
        ),
        migrations.AlterField(
            model_name='article',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian'), ('ru-uz', 'Russian-Uzbek')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian'), ('ru-uz', 'Russian-Uzbek')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='translate',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian'), ('ru-uz', 'Russian-Uzbek')], max_length=15, null=True),
        ),
    ]
