# Generated by Django 5.0.4 on 2024-09-17 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_speechtotextforbot_remove_speechtotext_lang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechtotextforbot',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='speechtotextforbot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
