# Generated by Django 5.0.4 on 2024-09-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_speechtotextforbot_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtotext',
            name='file_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speechtotext',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian'), ('ru-uz', 'Russian-Uzbek')], max_length=15, null=True),
        ),
    ]
