# Generated by Django 5.0.4 on 2024-09-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_speechtotext_file_duration_speechtotext_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtotextforbot',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
