# Generated by Django 5.0.4 on 2024-10-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_speechtotextforbot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='article_type',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('interview', 'Interview'), ('news', 'News'), ('reportage', 'Reportage')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian'), ('ru-uz', 'Russian-Uzbek')], max_length=15, null=True),
        ),
    ]
