# Generated by Django 5.0.4 on 2024-10-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_project_article_type_project_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='loading',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
