# Generated by Django 5.0.4 on 2024-10-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_project_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtotextforbot',
            name='lang',
            field=models.CharField(blank=True, choices=[('uz-UZ', 'Uzbek'), ('en-US', 'English'), ('ru-RU', 'Russian'), ('ru-uz', 'Russian-Uzbek')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='speechtotextforbot',
            name='type',
            field=models.CharField(blank=True, choices=[('stt', 'Speech To Text'), ('summary', 'Summary'), ('article', 'Article'), ('interview', 'Interview'), ('news', 'News'), ('reportage', 'Reportage')], max_length=30, null=True),
        ),
    ]
