# Generated by Django 5.1.2 on 2024-11-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_promocode_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.promocode'),
        ),
    ]
