# Generated by Django 5.1.2 on 2024-12-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_channelsubscribes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelsubscribes',
            old_name='free_bonus',
            new_name='is_subscribe',
        ),
    ]
