# Generated by Django 5.1.2 on 2025-02-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_free_bonus_channelsubscribes_is_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accepted_privacy',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
